### ISSUE TITLE
Evaluate models on analogical problem-solving

### ISSUE THREAD

**Issue by xinbowu2** [taylorwwebb/emergent_analogies_LLM#3]
Hi, thanks for sharing the codes and datasets. I'd also like to know how to evaluate models on analogical problem-solving.

**Comment by taylorwwebb** [comment]
This evaluation was performed in the OpenAI playground: https://platform.openai.com/playground see section 4.7 of the paper: https://arxiv.org/abs/2212.09196

**Comment by xinbowu2** [comment]
Thank you for the instructions!
